server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp
    username: root
    password: taolathuc123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
        format-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages :
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
api:
  prefix: api/v1
jwt:
  expiration : 2592000
  secretKey: scrobwoI/xAgwDqhMTPXqBT2DmaDPcbYWJlmhdo+CQk=




































